### ISSUE TITLE
Task not starting - marked as queued

### ISSUE THREAD

**Issue by hegusung** [hashview/hashview#208]
Hi, 

With my install hashview doesn't find the correct uploaded hash file, the uploaded hash file path is in "control/hashes/hashfile_upload_job_id-10-i1kcekuz.txt" while it is expecting it to be at "control/hashes/hashfile_11_2.txt"

here is the command line printed : 
`/opt/hashcat-3.30/hashcat64.bin -m 0 --potfile-disable --status-timer=15 --outfile-format 3  --outfile control/outfiles/hc_cracked_11_2.txt  -r control/rules/best64.rule control/hashes/hashfile_11_2.txt control/wordlists/password -w 3`

Hashcat works fine when replacing "control/hashes/hashfile_11_2.txt" with "control/hashes/hashfile_upload_job_id-10-i1kcekuz.txt"

any idea why the path is wrong ?

**Comment by ccammilleri** [comment]
ya I'm guessing somewhere in our code we accidentally referenced the temporary upload path vs the dynamically generated path upon executing hashcat.

@i128 will take a look this today :-)

**Comment by i128** [comment]
In hashview, navigate to the hashfile section and see how many hashes are listed. Does it show 0/0?

**Comment by hegusung** [comment]
No, the correct number of hashes is indicated

**Comment by i128** [comment]
I'm having problems recreating the problem on my end. What happens if you remove the hashfile, re-upload it, edit the job with the new hashfile and run the job?

**Comment by i128** [comment]
Also what branch are you on?

**Comment by hegusung** [comment]
Same issue when I remove and re-upload it, tried it several times, I am on the master branch

**Comment by i128** [comment]
Issue should now be resolved.

Do a 
`git pull`

To get the latest code, and then run the upgrade instructions found here:

https://github.com/hashview/hashview/wiki/Upgrading-Hashview

**Comment by ccammilleri** [comment]
closing. sounds like this was a isolated incident (maybe due to upgrading). reopen if this continues to happen with newly created jobs.

**Comment by hegusung** [comment]
I manage to install hashview properly on an ubuntu server but it still fails on my mint (pulled the sources yesterday)

I took time to investigate more, It seems the hashcat worker fails to contact the web API, it blocks right after RestClient performs a post for the heartbeat (doesn't return anything, the web server doesn't seem to get the request). Manual POST request to the API using curl and the same url works (added a print in the code).

In the web Interface under the agent tab the last heartbeat is blank, it seems to confirm my suspicions

I stopped my firewall and didn't solve anything, is anyone aware of some issues with ruby RestClient ?
